defaults: &defaults
  docker:
    - image: opuscapita/minsk-core-ci:2
      auth:
        username: $DOCKER_USER
        password: $DOCKER_PASS
  working_directory: ~/build

version: 2
jobs:
  init:
    docker:
      - image: opuscapita/minsk-core-machineuser-env:2
    steps:
      - run:
          name: Inject secrets from vault to CircleCI project's environment
          command: circle_ci_add_env.sh

  build:
    <<: *defaults
    steps:
      - run:
          name: Environment inject.
          command: env_inject.sh

      - checkout

      - restore_cache:
          keys:
            - react-reference-select-v1-{{ .Branch }}-{{ checksum "package.json" }}
            - react-reference-select-v1-{{ .Branch }}
            - react-reference-select-v1

      - run:
          name: "Installing dependencies."
          command: yarn install

      - save_cache:
          key: react-reference-select-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
              - ./node_modules
              - ./yarn.lock

      - run:
          name: "Running lint."
          command: npm run lint

      - run:
          name: Test
          command: |
            mkdir junit
            npm test -- --ci --testResultsProcessor='jest-junit-reporter'
          environment:
            TEST_REPORT_PATH: junit
            TEST_REPORT_FILENAME: test-results.xml

      - store_test_results:
          path: junit

      - store_artifacts:
          path: junit

  update-gh-pages:
    <<: *defaults
    steps:
      - run:
          name: Environment inject
          command: /bin/env_inject.sh
      
      - checkout

      - restore_cache:
          keys:
            - react-reference-select-v1-{{ .Branch }}-{{ checksum "package.json" }}
            - react-reference-select-v1-{{ .Branch }}
            - react-reference-select-v1

      - run:
          name: "Installing dependencies."
          command: yarn install

      - save_cache:
          key: react-reference-select-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
              - ./node_modules
              - ./yarn.lock

      - run:
          name: deploy-gh-pages
          command: npm run gh-pages-deploy

  build_release:
    <<: *defaults
    steps:
      - run:
          name: Environment inject
          command: /bin/env_inject.sh

      - checkout

      - restore_cache:
          keys:
            - react-reference-select-{{ .Branch }}-{{ checksum "package.json" }}
            - react-reference-select-{{ .Branch }}
            - react-reference-select

      - run:
          name: "Installing dependencies."
          command: yarn install

      - save_cache:
          key: react-reference-select-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
              - ./node_modules
              - ./yarn.lock

      - run:
          name: "Running lint."
          command: npm run lint

      - run:
          name: Test
          command: |
            mkdir junit
            npm test -- --ci --testResultsProcessor='jest-junit-reporter'
          environment:
            TEST_REPORT_PATH: junit
            TEST_REPORT_FILENAME: test-results.xml

      - store_test_results:
          path: junit

      - store_artifacts:
          path: junit

      - run:
          name: "Deploy."
          command: npm run publish-release

  release:
    <<: *defaults
    steps:

      - run:
          name: Environment inject
          command: env_inject.sh

      - checkout

      - run:
          name: Executing release scrtipt.
          command: .circleci/release.sh

workflows:
  version: 2
  release-and-build:
    jobs:
      - init:
          filters:
            tags:
              only: /.*/
      - release:
          filters:
            branches:
              only: release
          requires:
            - init
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
                - release
          requires:
            - init
      - update-gh-pages:
          filters:
            branches:
              ignore:
                - gh-pages
                - release
          requires:
            - init
            - build
      - build_release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          requires:
            - init
