version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: circleci/node:6
    working_directory: ~/reference-select
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Test
          command: |
            mkdir junit
            npm test -- --ci --testResultsProcessor='jest-junit-reporter'
          environment:
            TEST_REPORT_PATH: junit
            TEST_REPORT_FILENAME: test-results.xml

      - store_test_results:
          path: junit

      - store_artifacts:
          path: junit
  update-gh-pages:
      branches:
        only:
          - master
      docker:
        - image: circleci/node:6
      working_directory: ~/reference-select
      steps:
        - checkout
        - restore_cache:
            keys:
            - dependencies-{{ checksum "package.json" }}

        - run:
            name: install-dependencies
            command: npm install

        - save_cache:
            key: dependencies-{{ checksum "package.json" }}
            paths:
              - node_modules

        - run:
            name: build-gh-pages
            command: ./scripts/gh-pages/build.sh

        - run:
            name: deploy-gh-pages
            command: ./scripts/gh-pages/deploy.sh .gh-pages-tmp

workflows:
  version: 2
  build-all:
    jobs:
      - update-gh-pages:
          requires:
            - build
